version: '3.8'

services:
  api-gateway:
    image: registry.gitlab.com/group/e-commerce-api-gateway-service:latest
    ports:
      - "5000:3000"
    environment:
      SERVICE_AUTH_URL: http://auth:3001
      SERVICE_PRODUCT_URL: http://product:3003

  auth:
    image: registry.gitlab.com/group/e-commerce-microservice:latest
    ports:
      - "3001:3001"
    environment:
      MONGO_URI: mongodb://mongodb:27017/auth

  product:
    image: registry.gitlab.com/group/e-commerce-product-service:latest
    ports:
      - "3003:3003"
    environment:
      MONGO_URI: mongodb://mongodb:27017/products

  mongodb:
    image: mongo:5
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: